export interface Libro {
    id_libro: number,
    autor: string,
    pais: string,
    portada: string,
    idioma: string,
    link: string,
    paginas: number,
    titulo: string,
    anio: number,
    ISBN: string,
    categoria: string,
    descripcion: string,
    precio: number,
    stock: number,
}