# Generated by Django 4.2 on 2024-06-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialpedido',
            old_name='fecha_cambio',
            new_name='fecha_pedido',
        ),
        migrations.RemoveField(
            model_name='historialpedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='id_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ecommerce.pedido'),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_pedido', to='ecommerce.libro'),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_pedido',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
